
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class changepassword extends javax.swing.JFrame {

    /**
     * Creates new form changepassword
     */
   String username1;
    public changepassword(String username) {
        initComponents();
         setSize(900,900);
         lbback1.setSize(900,900);
        setLocationRelativeTo(null);
        setVisible(true);
         this.username1=username;
        tfusername.setText(username1);
        tfusername.setEditable(false);
       // this.username1=username;
          setDefaultCloseOperation(EXIT_ON_CLOSE);
          
          ImageIcon icon=new ImageIcon("src/backpic/img5.jpg");
          Image img=icon.getImage();
          Image scaledimg=img.getScaledInstance(lbback1.getWidth(), lbback1.getHeight(), Image.SCALE_SMOOTH);
          lbback1.setIcon(new ImageIcon(scaledimg));
         setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        changepassword = new javax.swing.JButton();
        tfoldpassword = new javax.swing.JPasswordField();
        tfnewpassword = new javax.swing.JPasswordField();
        tfconfirmpassword = new javax.swing.JPasswordField();
        lbback1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 140, 40);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel2.setText("Old password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 200, 190, 40);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel3.setText("New password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 320, 180, 40);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel4.setText("Confirm password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 440, 240, 50);

        tfusername.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        getContentPane().add(tfusername);
        tfusername.setBounds(470, 70, 210, 50);

        changepassword.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        changepassword.setText("Change password");
        changepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswordActionPerformed(evt);
            }
        });
        getContentPane().add(changepassword);
        changepassword.setBounds(240, 580, 250, 50);

        tfoldpassword.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        getContentPane().add(tfoldpassword);
        tfoldpassword.setBounds(470, 200, 210, 50);

        tfnewpassword.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        getContentPane().add(tfnewpassword);
        tfnewpassword.setBounds(470, 310, 210, 50);

        tfconfirmpassword.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        getContentPane().add(tfconfirmpassword);
        tfconfirmpassword.setBounds(470, 440, 210, 50);
        getContentPane().add(lbback1);
        lbback1.setBounds(0, 0, 760, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswordActionPerformed
        // TODO add your handling code here:
        
        String oldpassword=tfoldpassword.getText();
        String newpassword=tfnewpassword.getText();
        String confirmpassword=tfconfirmpassword.getText();
        if(oldpassword.isEmpty()||newpassword.isEmpty()||confirmpassword.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"please fill all fields");
        }
        else if(newpassword.equals(confirmpassword))
        {
            try{
                  HttpResponse<String> httpResponse = Unirest.get("http://localhost:8888/changepassword")
                          .queryString("oldpass",oldpassword)
                          .queryString("newpass",newpassword)
                          .queryString("username",username1)
                          .asString();
                  String msg=httpResponse.getBody();
                  System.out.println("msg "+msg);
                  if(msg.equals("success"))
                  {
                                 dispose();

                      login obj=new login();
                      obj.setVisible(true);
                  }
                  else
                  {
                      JOptionPane.showMessageDialog(this,"username or password is wrong");
                  }
                
            }
            catch(UnirestException ex)
            {
                ex.printStackTrace();
//                Logger.getLogger(changepassword.getName()).log(Level.SEVERE,null,ex);
            }
        }
    }//GEN-LAST:event_changepasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new changepassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changepassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbback1;
    private javax.swing.JPasswordField tfconfirmpassword;
    private javax.swing.JPasswordField tfnewpassword;
    private javax.swing.JPasswordField tfoldpassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
