
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ACER
 */
public class editprofile extends javax.swing.JFrame {
String photo;
    /**
     * Creates new form editprofile
     */
    File f1;
    String username;
    public editprofile(String Username) {
        initComponents();
                   this.username = Username;

         setSize(900,900);
         lbback1.setSize(900,900);
           setLocationRelativeTo(null);
        tfusername.setText(username);
        tfusername.setFocusable(false);
        new Thread(new setprofile()).start();
        setVisible(true);
          setDefaultCloseOperation(DISPOSE_ON_CLOSE);
          
          
          
          ImageIcon icon=new ImageIcon("src/backpic/img19.jpg");
          Image img=icon.getImage();
          Image scaledimg=img.getScaledInstance(lbback1.getWidth(), lbback1.getHeight(), Image.SCALE_SMOOTH);
          lbback1.setIcon(new ImageIcon(scaledimg));
         setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        tfphoneno = new javax.swing.JTextField();
        buttonbrowse = new javax.swing.JButton();
        buttonsubmit = new javax.swing.JButton();
        lbphoto = new javax.swing.JLabel();
        lbback1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 80, 140, 30);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 200, 110, 40);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel3.setText("phone no");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 320, 140, 40);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel4.setText("photo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 430, 100, 40);

        tfusername.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        getContentPane().add(tfusername);
        tfusername.setBounds(419, 72, 180, 40);

        tfemail.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        getContentPane().add(tfemail);
        tfemail.setBounds(420, 190, 250, 50);

        tfphoneno.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        getContentPane().add(tfphoneno);
        tfphoneno.setBounds(420, 320, 190, 50);

        buttonbrowse.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        buttonbrowse.setText("Browse");
        buttonbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(buttonbrowse);
        buttonbrowse.setBounds(420, 435, 160, 50);

        buttonsubmit.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        buttonsubmit.setText("submit");
        buttonsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonsubmit);
        buttonsubmit.setBounds(230, 570, 130, 50);

        lbphoto.setText("jLabel5");
        getContentPane().add(lbphoto);
        lbphoto.setBounds(250, 410, 130, 90);
        getContentPane().add(lbback1);
        lbback1.setBounds(0, 0, 790, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsubmitActionPerformed
        // TODO add your handling code here:
        String name = tfusername.getText();
        String email = tfemail.getText();
        String phoneno = tfphoneno.getText();

        {
            try {
                HttpResponse<String> httpResponse = Unirest.post("http://localhost:8888/editprofile")
                        .queryString("name", name)
                        .queryString("email", email)
                        .queryString("phoneno", phoneno)
                        .field("photo", new File(photo))
                        .asString();

                String msg = httpResponse.getBody();

                if (msg.equals("success")) {
                    JOptionPane.showMessageDialog(this, "Updated Successfully");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error in Updation");

                }

            } catch (Exception ae) {
                ae.printStackTrace();
            }
        }
    }//GEN-LAST:event_buttonsubmitActionPerformed

    private void buttonbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbrowseActionPerformed
        // TODO add your handling code here:
         JFileChooser fc=new JFileChooser();
      int ans= fc.showOpenDialog(this);
      if(ans==JFileChooser.APPROVE_OPTION){
             try {
                 //      fc.getSelectedFile();
                 f1=fc.getSelectedFile();
                 System.out.println(f1.getPath());
                 photo=f1.getPath();
                 BufferedImage img=ImageIO.read(f1);
                   BufferedImage newimg = resize(img, lbphoto.getWidth(), lbphoto.getHeight());
                   lbphoto.setIcon(new ImageIcon(newimg));
        
//                 lbphoto.setText(f1.getPath());
             } catch (IOException ex) {
//                 Logger.getLogger(editprofile.class.getName()).log(Level.SEVERE, null, ex);
             ex.printStackTrace();
             }
      }
    }//GEN-LAST:event_buttonbrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new editprofile().setVisible(true);
            }
        });
    }
class setprofile implements Runnable
{

        @Override
        public void run() {
           // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          try{
           HttpResponse<String> httpResponse = Unirest.get(globalclass.ip + "/profileset")
                   .queryString("username",username)
                                      .asString();
          if(httpResponse.getStatus()==200){
              String res=httpResponse.getBody();
              StringTokenizer st=new StringTokenizer(res,";");
              String email=st.nextToken();
              String phno=st.nextToken();
               photo=st.nextToken();
              tfemail.setText(email);
              tfphoneno.setText(phno);
             URL url = new URL(globalclass.ip + "/GetResource/" + photo);
                        BufferedImage image = ImageIO.read(url);
                        BufferedImage newimg = resize(image, lbphoto.getWidth(), lbphoto.getHeight());
                   lbphoto.setIcon(new ImageIcon(newimg));
          }
          
          }
          catch(Exception ex){
              ex.printStackTrace();
          }
                   
                    
        }
    
}
BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonbrowse;
    private javax.swing.JButton buttonsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbback1;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfphoneno;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
