
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
public class FiltersDemo extends javax.swing.JFrame {

    JFileChooser jfc;
    File f;
    BufferedImage changedimg, img, resizedimg;

    /**
     * Creates new form FiltersDemo
     */
    public FiltersDemo() {
        initComponents();
        setSize(600,600);
        btsave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btbrowse = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btbrighter = new javax.swing.JButton();
        btdarken = new javax.swing.JButton();
        btsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 40, 110, 100);

        btbrowse.setText("Browse");
        btbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btbrowse);
        btbrowse.setBounds(230, 63, 110, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        btbrighter.setText("Brighter");
        btbrighter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbrighterActionPerformed(evt);
            }
        });
        jPanel1.add(btbrighter);
        btbrighter.setBounds(30, 30, 140, 40);

        btdarken.setText("Darken");
        btdarken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdarkenActionPerformed(evt);
            }
        });
        jPanel1.add(btdarken);
        btdarken.setBounds(200, 30, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 200, 440, 150);

        btsave.setText("Save changes");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btsave);
        btsave.setBounds(230, 113, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbrowseActionPerformed
        jfc = new JFileChooser();
        int ans = jfc.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            try {
                
                img = ImageIO.read(f);
                BufferedImage newimg = resize(img, jLabel1.getWidth(), jLabel1.getHeight());
                jLabel1.setIcon(new ImageIcon(newimg));
                        btsave.setEnabled(false);

            } catch (IOException ex) {

                ex.printStackTrace();

            }
        }


    }//GEN-LAST:event_btbrowseActionPerformed

    private void btbrighterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbrighterActionPerformed
        BrighterFilter obj = new BrighterFilter();
        changedimg = obj.filter(img);
        resizedimg = resize(changedimg, jLabel1.getWidth(), jLabel1.getHeight());
        jLabel1.setIcon(new ImageIcon(resizedimg));
        repaint();
        btsave.setEnabled(true);


    }//GEN-LAST:event_btbrighterActionPerformed

    private void btdarkenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdarkenActionPerformed
        DarkerFilter obj = new DarkerFilter();
        changedimg = obj.filter(img);
        resizedimg = resize(changedimg, jLabel1.getWidth(), jLabel1.getHeight());
        jLabel1.setIcon(new ImageIcon(resizedimg));
        repaint();
        btsave.setEnabled(true);

    }//GEN-LAST:event_btdarkenActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed


    }//GEN-LAST:event_btsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiltersDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiltersDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiltersDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiltersDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FiltersDemo().setVisible(true);
            }
        });
    }

    BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbrighter;
    private javax.swing.JButton btbrowse;
    private javax.swing.JButton btdarken;
    private javax.swing.JButton btsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
