
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class firstpage extends javax.swing.JFrame {

    /**
     * Creates new form firstpage
     */
    public firstpage() {
        initComponents();
        setSize(900,900);
        lbback2.setSize(900,900);
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        
         ImageIcon icon=new ImageIcon("src/backpic/image1.jpg");
          Image img=icon.getImage();
          Image scaledimg=img.getScaledInstance(lbback2.getWidth(), lbback2.getHeight(), Image.SCALE_SMOOTH);
          lbback2.setIcon(new ImageIcon(scaledimg));
         setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newuserbutton = new javax.swing.JButton();
        existinguserbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbback2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        newuserbutton.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        newuserbutton.setText("New User");
        newuserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newuserbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(newuserbutton);
        newuserbutton.setBounds(120, 380, 190, 50);

        existinguserbutton.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        existinguserbutton.setText("Existing User");
        existinguserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existinguserbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(existinguserbutton);
        existinguserbutton.setBounds(570, 380, 210, 50);

        jLabel1.setBackground(new java.awt.Color(204, 255, 51));
        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 102));
        jLabel1.setText("WELCOME IN INSTA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 130, 300, 40);
        getContentPane().add(lbback2);
        lbback2.setBounds(0, 0, 830, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newuserbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newuserbuttonActionPerformed
        // TODO add your handling code here:
         dispose();
        signup obj=new signup();
        obj.setVisible(true);
    }//GEN-LAST:event_newuserbuttonActionPerformed

    private void existinguserbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existinguserbuttonActionPerformed
        // TODO add your handling code here:
         dispose();
        login obj=new login();
        obj.setVisible(true);
    }//GEN-LAST:event_existinguserbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton existinguserbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbback2;
    private javax.swing.JButton newuserbutton;
    // End of variables declaration//GEN-END:variables
}
