/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class panel2 extends javax.swing.JPanel {

    /**
     * Creates new form panel2
     */
    public panel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbphoto1 = new javax.swing.JLabel();
        btclose = new javax.swing.JButton();
        lbcaption = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setLayout(null);

        lbphoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbphoto1);
        lbphoto1.setBounds(0, 20, 150, 140);

        btclose.setText("x");
        add(btclose);
        btclose.setBounds(170, 20, 39, 25);
        add(lbcaption);
        lbcaption.setBounds(20, 200, 170, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btclose;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel lbcaption;
    public javax.swing.JLabel lbphoto1;
    // End of variables declaration//GEN-END:variables
}
