
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Image;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form frame2
     */
    File f1;
    public signup() {
        initComponents();
        setSize(900,900);
        lbback1.setSize(900,900);
        setLocationRelativeTo(null);
        setVisible(true);
        questbox.removeAllItems();
        for(int i=0;i<globalclass.ques.length;i++){
            questbox.addItem(globalclass.ques[i]);
              setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
        }
        
        
        ImageIcon icon=new ImageIcon("src/backpic/img5.jpg");
          Image img=icon.getImage();
          Image scaledimg=img.getScaledInstance(lbback1.getWidth(), lbback1.getHeight(), Image.SCALE_SMOOTH);
          lbback1.setIcon(new ImageIcon(scaledimg));
         setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfname = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        tfmobileno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfsecurityans = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        submitbutton = new javax.swing.JButton();
        browsebutton = new javax.swing.JButton();
        lb1 = new javax.swing.JTextField();
        questbox = new javax.swing.JComboBox<>();
        confirmpassword = new javax.swing.JPasswordField();
        tfpassword = new javax.swing.JPasswordField();
        lbback1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfname.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfname);
        tfname.setBounds(410, 50, 230, 40);

        tfemail.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        tfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailActionPerformed(evt);
            }
        });
        getContentPane().add(tfemail);
        tfemail.setBounds(410, 130, 340, 40);

        tfmobileno.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        tfmobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmobilenoActionPerformed(evt);
            }
        });
        getContentPane().add(tfmobileno);
        tfmobileno.setBounds(410, 380, 210, 40);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 50, 100, 40);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 130, 120, 40);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel3.setText("password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 220, 130, 40);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel4.setText("Confirm-Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 310, 240, 40);

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel5.setText("Mobile Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 380, 220, 40);

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel6.setText("Security Question");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 450, 250, 50);

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel7.setText("Security Answer");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 540, 240, 50);

        tfsecurityans.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        tfsecurityans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsecurityansActionPerformed(evt);
            }
        });
        getContentPane().add(tfsecurityans);
        tfsecurityans.setBounds(410, 540, 200, 40);

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel8.setText("Photo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 630, 110, 50);

        submitbutton.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(submitbutton);
        submitbutton.setBounds(310, 740, 160, 50);

        browsebutton.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        browsebutton.setText("Browse");
        browsebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(browsebutton);
        browsebutton.setBounds(480, 640, 170, 40);

        lb1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb1ActionPerformed(evt);
            }
        });
        getContentPane().add(lb1);
        lb1.setBounds(170, 640, 200, 40);

        questbox.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        questbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        questbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questboxActionPerformed(evt);
            }
        });
        getContentPane().add(questbox);
        questbox.setBounds(410, 460, 170, 40);

        confirmpassword.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        getContentPane().add(confirmpassword);
        confirmpassword.setBounds(410, 300, 210, 40);

        tfpassword.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        getContentPane().add(tfpassword);
        tfpassword.setBounds(410, 220, 210, 40);
        getContentPane().add(lbback1);
        lbback1.setBounds(0, 0, 770, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void tfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailActionPerformed

    private void browsebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebuttonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc=new JFileChooser();
      int ans= fc.showOpenDialog(this);
      if(ans==JFileChooser.APPROVE_OPTION){
//      fc.getSelectedFile();
      f1=fc.getSelectedFile();
          System.out.println(f1.getPath());
      lb1.setText(f1.getPath());
      
      }
      
       
    }//GEN-LAST:event_browsebuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        String name=tfname.getText();
        String email=tfemail.getText();
        String password=tfpassword.getText();
        String cpass=confirmpassword.getText();
        String mobile=tfmobileno.getText();
        String securityans =tfsecurityans.getText();
        String securityques=questbox.getSelectedItem().toString();
        String path=lb1.getText();
        if(name.isEmpty()||email.isEmpty()||password.isEmpty()||mobile.isEmpty()||securityans.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"please fill all the field");
        }
        else if(password.equals(cpass))
                {
            try {
                HttpResponse<String> httpResponse = Unirest.post("http://localhost:8888/SignUp")
                        .queryString("email", email)
                        .queryString("name", name)
                        .queryString("password", password)
                        .queryString("mobile", mobile)
                        .queryString("secq",securityques)
                        .queryString("securityans",securityans)
                        .field("photo",f1)
                        .asString();
                String msg=httpResponse.getBody();
                if(msg.equals("success"))
                {
                    JOptionPane.showMessageDialog(rootPane,"signup successfull");
                    login obj=new login();
                    obj.setVisible(true);
                }
                
            } catch (UnirestException ex) {
               ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void tfmobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmobilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmobilenoActionPerformed

    private void questboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questboxActionPerformed

    private void tfsecurityansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsecurityansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsecurityansActionPerformed

    private void lb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browsebutton;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lb1;
    private javax.swing.JLabel lbback1;
    private javax.swing.JComboBox<String> questbox;
    private javax.swing.JButton submitbutton;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfmobileno;
    private javax.swing.JTextField tfname;
    private javax.swing.JPasswordField tfpassword;
    private javax.swing.JTextField tfsecurityans;
    // End of variables declaration//GEN-END:variables
}
